### ISSUE TITLE
Cargar Proyecto en Visual Studio 2019

### ISSUE THREAD

**Issue by AlexVillegas** [Asuskf/Sistema-Contable-Arcano#3]
Intente Cargar el proyecto en Visual Studio, pero dio muchos errores :

"..Error		No se puede procesar el archivo ELRFormRegistro.resx porque está en Internet o en una zona restringida, o bien tiene la marca de la Web. Quite esta marca si desea procesar los archivos.	WinControl_ELR_NET			
.."

**Comment by Asuskf** [comment]
Lamentamos escuchar eso pero el proyecto fue abandonado hace mucho tiempo. Por el momento ningun de los 2 desarrolladores tenemos windows es por ello que no es posible arreglar tu issue :(
